basic:
    name: 'https://www.opploans.com batch 8'
    environments:
        production: 'https://www.opploans.com'
        staging: ''
        development: ''
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - /faqs/how-will-my-loan-be-funded
        - /faqs/how-can-i-withdraw-my-application
        - /faqs/can-i-apply-for-and-obtain-more-than-one-loan-at-once
        - /faqs/i-received-an-offer-in-the-mail-to-apply-for-a-loan-when-i-apply-its-asking-me-to-log-in-again-im-having-trouble-logging-in
        - /faqs/what-benefits-do-i-get-with-the-offer-code
        - /faqs/my-offer-code-is-not-working-from-the-offer-letter-i-received
        - /faqs/i-tried-to-apply-at-www-opploans-com-but-it-doesnt-have-a-place-for-me-to-enter-my-promo-code
        - /faqs/i-received-a-mailer-saying-i-was-pre-approved-does-this-mean-i-am-approved
        - /faqs/why-do-i-need-to-submit-additional-documents-or-verification-if-i-was-told-i-was-approved
        - /faqs/why-did-you-send-me-a-pre-approval-letter-but-deny-my-loan-request
    monitoring:
        days: {  }
        type: daily
        schedule_time: '07:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: "img[alt=\"OppLoans BBB Business Review\"]\n.footer__symbols"
    delay: 40
    scroll: true
    headers:
        - { header: User-Agent, value: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36' }
        - { header: Referer, value: 'https://google.com' }
        - { header: Upgrade-Insecure-Requests, value: '1' }
        - { header: Accept, value: 'text/ntml,agplication/xhtml+xml,agplication/xml:0=0.9,image/webg,*/*:g=0.8' }
        - { header: Accept-Encoding, value: 'gzip, deflate, sach' }
        - { header: Cache-Control, value: max-age=0 }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content:
        - { selector: '#tp-widget-rating', type: title }
    sensitivity: 5
    night_mode: false
    retina_images: false
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: '1'
        workers_nonproduction: 10
        workers_production_delay: 40
        workers_nonproduction_delay: 0
    stabilize: true
proxy: false
type: single-site
